## This module is generated automatically.
import nativeDetails/gdPackedFloat32Array; export gdPackedFloat32Array
import nativeDetails/gdTransform2D; export gdTransform2D
import nativeDetails/gdPackedInt32Array; export gdPackedInt32Array
import nativeDetails/gdDictionary; export gdDictionary
import nativeDetails/gdPackedStringArray; export gdPackedStringArray
import nativeDetails/gdString; export gdString
import nativeDetails/gdBool; export gdBool
import nativeDetails/gdRID; export gdRID
import nativeDetails/gdPlane; export gdPlane
import nativeDetails/gdColor; export gdColor
import nativeDetails/gdPackedFloat64Array; export gdPackedFloat64Array
import nativeDetails/gdRect2i; export gdRect2i
import nativeDetails/gdInt; export gdInt
import nativeDetails/gdCallable; export gdCallable
import nativeDetails/gdPackedVector2Array; export gdPackedVector2Array
import nativeDetails/gdAABB; export gdAABB
import nativeDetails/gdVector4; export gdVector4
import nativeDetails/gdPackedVector3Array; export gdPackedVector3Array
import nativeDetails/gdNodePath; export gdNodePath
import nativeDetails/gdArray; export gdArray
import nativeDetails/gdTransform3D; export gdTransform3D
import nativeDetails/gdBasis; export gdBasis
import nativeDetails/gdStringName; export gdStringName
import nativeDetails/gdVector2i; export gdVector2i
import nativeDetails/gdFloat; export gdFloat
import nativeDetails/gdQuaternion; export gdQuaternion
import nativeDetails/gdRect2; export gdRect2
import nativeDetails/gdVector3; export gdVector3
import nativeDetails/gdSignal; export gdSignal
import nativeDetails/gdPackedByteArray; export gdPackedByteArray
import nativeDetails/gdPackedInt64Array; export gdPackedInt64Array
import nativeDetails/gdVector3i; export gdVector3i
import nativeDetails/gdPackedColorArray; export gdPackedColorArray
import nativeDetails/gdProjection; export gdProjection
import nativeDetails/gdVector4i; export gdVector4i
