import ../pure/todos
import variantsDetail_custom/variantsDetail_vectors; export variantsDetail_vectors
import variantsDetail_custom/variantsDetail_primitives; export variantsDetail_primitives
import variantsDetail_custom/variantsDetail_stringUtils; export variantsDetail_stringUtils

TODO Implement_primitive_variants