import ../pure/todos
import variantsDetail_custom/variantsDetail_vectors; export variantsDetail_vectors
import variantsDetail_custom/variantsDetail_primitives; export variantsDetail_primitives

TODO with Implement_primitive_variants