# ======================================== #
# This module was generated automatically. #
# Edits will be lost.                      #
# ======================================== #
import ./../helper/engineClassDefiner

define_godot_engine_class_essencials(PhysicsDirectBodyState2DExtension, PhysicsDirectBodyState2D)
method getTotalGravity*(self: PhysicsDirectBodyState2DExtension): Vector2 {.base.} = (discard)
method getTotalLinearDamp*(self: PhysicsDirectBodyState2DExtension): Float {.base.} = (discard)
method getTotalAngularDamp*(self: PhysicsDirectBodyState2DExtension): Float {.base.} = (discard)
method getCenterOfMass*(self: PhysicsDirectBodyState2DExtension): Vector2 {.base.} = (discard)
method getCenterOfMassLocal*(self: PhysicsDirectBodyState2DExtension): Vector2 {.base.} = (discard)
method getInverseMass*(self: PhysicsDirectBodyState2DExtension): Float {.base.} = (discard)
method getInverseInertia*(self: PhysicsDirectBodyState2DExtension): Float {.base.} = (discard)
method setLinearVelocity*(self: PhysicsDirectBodyState2DExtension; velocity: Vector2) {.base.} = (discard)
method getLinearVelocity*(self: PhysicsDirectBodyState2DExtension): Vector2 {.base.} = (discard)
method setAngularVelocity*(self: PhysicsDirectBodyState2DExtension; velocity: Float) {.base.} = (discard)
method getAngularVelocity*(self: PhysicsDirectBodyState2DExtension): Float {.base.} = (discard)
method setTransform*(self: PhysicsDirectBodyState2DExtension; transform: Transform2D) {.base.} = (discard)
method getTransform*(self: PhysicsDirectBodyState2DExtension): Transform2D {.base.} = (discard)
method getVelocityAtLocalPosition*(self: PhysicsDirectBodyState2DExtension; localPosition: Vector2): Vector2 {.base.} = (discard)
method applyCentralImpulse*(self: PhysicsDirectBodyState2DExtension; impulse: Vector2) {.base.} = (discard)
method applyImpulse*(self: PhysicsDirectBodyState2DExtension; impulse: Vector2; position: Vector2) {.base.} = (discard)
method applyTorqueImpulse*(self: PhysicsDirectBodyState2DExtension; impulse: Float) {.base.} = (discard)
method applyCentralForce*(self: PhysicsDirectBodyState2DExtension; force: Vector2) {.base.} = (discard)
method applyForce*(self: PhysicsDirectBodyState2DExtension; force: Vector2; position: Vector2) {.base.} = (discard)
method applyTorque*(self: PhysicsDirectBodyState2DExtension; torque: Float) {.base.} = (discard)
method addConstantCentralForce*(self: PhysicsDirectBodyState2DExtension; force: Vector2) {.base.} = (discard)
method addConstantForce*(self: PhysicsDirectBodyState2DExtension; force: Vector2; position: Vector2) {.base.} = (discard)
method addConstantTorque*(self: PhysicsDirectBodyState2DExtension; torque: Float) {.base.} = (discard)
method setConstantForce*(self: PhysicsDirectBodyState2DExtension; force: Vector2) {.base.} = (discard)
method getConstantForce*(self: PhysicsDirectBodyState2DExtension): Vector2 {.base.} = (discard)
method setConstantTorque*(self: PhysicsDirectBodyState2DExtension; torque: Float) {.base.} = (discard)
method getConstantTorque*(self: PhysicsDirectBodyState2DExtension): Float {.base.} = (discard)
method setSleepState*(self: PhysicsDirectBodyState2DExtension; enabled: Bool) {.base.} = (discard)
method isSleeping*(self: PhysicsDirectBodyState2DExtension): Bool {.base.} = (discard)
method getContactCount*(self: PhysicsDirectBodyState2DExtension): int32 {.base.} = (discard)
method getContactLocalPosition*(self: PhysicsDirectBodyState2DExtension; contactIdx: int32): Vector2 {.base.} = (discard)
method getContactLocalNormal*(self: PhysicsDirectBodyState2DExtension; contactIdx: int32): Vector2 {.base.} = (discard)
method getContactLocalShape*(self: PhysicsDirectBodyState2DExtension; contactIdx: int32): int32 {.base.} = (discard)
method getContactLocalVelocityAtPosition*(self: PhysicsDirectBodyState2DExtension; contactIdx: int32): Vector2 {.base.} = (discard)
method getContactCollider*(self: PhysicsDirectBodyState2DExtension; contactIdx: int32): RID {.base.} = (discard)
method getContactColliderPosition*(self: PhysicsDirectBodyState2DExtension; contactIdx: int32): Vector2 {.base.} = (discard)
method getContactColliderId*(self: PhysicsDirectBodyState2DExtension; contactIdx: int32): uint64 {.base.} = (discard)
method getContactColliderObject*(self: PhysicsDirectBodyState2DExtension; contactIdx: int32): Object {.base.} = (discard)
method getContactColliderShape*(self: PhysicsDirectBodyState2DExtension; contactIdx: int32): int32 {.base.} = (discard)
method getContactColliderVelocityAtPosition*(self: PhysicsDirectBodyState2DExtension; contactIdx: int32): Vector2 {.base.} = (discard)
method getContactImpulse*(self: PhysicsDirectBodyState2DExtension; contactIdx: int32): Vector2 {.base.} = (discard)
method getStep*(self: PhysicsDirectBodyState2DExtension): Float {.base.} = (discard)
method integrateForces*(self: PhysicsDirectBodyState2DExtension) {.base.} = (discard)
method getSpaceState*(self: PhysicsDirectBodyState2DExtension): PhysicsDirectSpaceState2D {.base.} = (discard)