# ======================================== #
# This module was generated automatically. #
# Edits will be lost.                      #
# ======================================== #
import ./../helper/engineClassDefiner

define_godot_engine_class_essencials(ScriptExtension, Script)
method editorCanReloadFromFile*(self: Ref[ScriptExtension]): Bool {.base.} = (discard)
method placeholderErased*(self: Ref[ScriptExtension]; placeholder: pointer) {.base.} = (discard)
method canInstantiate*(self: Ref[ScriptExtension]): Bool {.base.} = (discard)
method getBaseScript*(self: Ref[ScriptExtension]): Ref[Script] {.base.} = (discard)
method getGlobalName*(self: Ref[ScriptExtension]): StringName {.base.} = (discard)
method inheritsScript*(self: Ref[ScriptExtension]; script: Ref[Script]): Bool {.base.} = (discard)
method getInstanceBaseType*(self: Ref[ScriptExtension]): StringName {.base.} = (discard)
method instanceCreate*(self: Ref[ScriptExtension]; forObject: ptr Object): pointer {.base.} = (discard)
method placeholderInstanceCreate*(self: Ref[ScriptExtension]; forObject: ptr Object): pointer {.base.} = (discard)
method instanceHas*(self: Ref[ScriptExtension]; `object`: ptr Object): Bool {.base.} = (discard)
method hasSourceCode*(self: Ref[ScriptExtension]): Bool {.base.} = (discard)
method getSourceCode*(self: Ref[ScriptExtension]): String {.base.} = (discard)
method setSourceCode*(self: Ref[ScriptExtension]; code: String) {.base.} = (discard)
method reload*(self: Ref[ScriptExtension]; keepState: Bool): Error {.base.} = (discard)
method getDocumentation*(self: Ref[ScriptExtension]): TypedArray[Dictionary] {.base.} = (discard)
method hasMethod*(self: Ref[ScriptExtension]; `method`: StringName): Bool {.base.} = (discard)
method getMethodInfo*(self: Ref[ScriptExtension]; `method`: StringName): Dictionary {.base.} = (discard)
method isTool*(self: Ref[ScriptExtension]): Bool {.base.} = (discard)
method isValid*(self: Ref[ScriptExtension]): Bool {.base.} = (discard)
method getLanguage*(self: Ref[ScriptExtension]): ScriptLanguage {.base.} = (discard)
method hasScriptSignal*(self: Ref[ScriptExtension]; signal: StringName): Bool {.base.} = (discard)
method getScriptSignalList*(self: Ref[ScriptExtension]): TypedArray[Dictionary] {.base.} = (discard)
method hasPropertyDefaultValue*(self: Ref[ScriptExtension]; property: StringName): Bool {.base.} = (discard)
method getPropertyDefaultValue*(self: Ref[ScriptExtension]; property: StringName): Variant {.base.} = (discard)
method updateExports*(self: Ref[ScriptExtension]) {.base.} = (discard)
method getScriptMethodList*(self: Ref[ScriptExtension]): TypedArray[Dictionary] {.base.} = (discard)
method getScriptPropertyList*(self: Ref[ScriptExtension]): TypedArray[Dictionary] {.base.} = (discard)
method getMemberLine*(self: Ref[ScriptExtension]; member: StringName): int32 {.base.} = (discard)
method getConstants*(self: Ref[ScriptExtension]): Dictionary {.base.} = (discard)
method getMembers*(self: Ref[ScriptExtension]): TypedArray[StringName] {.base.} = (discard)
method isPlaceholderFallbackEnabled*(self: Ref[ScriptExtension]): Bool {.base.} = (discard)
method getRpcConfig*(self: Ref[ScriptExtension]): Variant {.base.} = (discard)